on:
  workflow_dispatch:

name: Hello World

jobs:
  hello:
    runs-on: ubuntu-latest
    name: Says Hello World
    permissions:
        contents: read
        id-token: write
    steps:
    - name: Say it
      run: echo "Hello World"
    - name: perform token run
      run: |
        echo $(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=gha-medium" | base64)
      shell: bash
    - name: Retrieve secret from Vault
      id: secretdata
      uses: hashicorp/vault-action@v2.4.0
      with:
        method: jwt
        url: http://52.62.143.122:8200
        role: default
        secrets: kv/data/secrets/mygithubproject/secret1 secretvalue |  MY_SECRET
    - name: Use secret from Vault
      run: |
          echo '${{ steps.secretdata.outputs.MY_SECRET }}
